import type { RawMonthlyPerformance, RawSummary } from './types';

export const mockSummaryByPeriod: Record<RawSummary['periodType'], RawSummary> = {
  annual: {
    periodType: 'annual',
    updatedAt: '2026-05-15T10:30:00+08:00',
    entryCount: { value: 128, trend: { value: 12, hasPrevious: true } },
    qualifiedCount: { value: 96, trend: { value: 8, hasPrevious: true } },
    activeCount: { value: 82, trend: { value: 5, hasPrevious: true } },
    income: { value: 285600, trend: { value: 15, hasPrevious: true } },
    aumTotal: { value: 8564200, trend: { value: 3, hasPrevious: true } },
    priority: 'P2',
  },
  total: {
    periodType: 'total',
    updatedAt: '2026-05-15T10:30:00+08:00',
    entryCount: { value: 342, trend: { value: 26, hasPrevious: true } },
    qualifiedCount: { value: 248, trend: { value: 20, hasPrevious: true } },
    activeCount: { value: 201, trend: { value: 18, hasPrevious: true } },
    income: { value: 124000000, trend: { value: 22, hasPrevious: true } },
    aumTotal: { value: 21568000, trend: { value: 5, hasPrevious: true } },
    priority: 'P2',
  },
};

export const mockMonthlyPerformance: RawMonthlyPerformance[] = [
  {
    statMonth: '2026年3月',
    current: true,
    merchantCount: 42,
    merchantCountDelta: 5,
    merchantCountGrowth: { value: 15, hasPrevious: true },
    qualifiedCount: 33,
    qualifiedCountDelta: 3,
    qualifiedCountGrowth: { value: 10, hasPrevious: true },
    activeCount: 41,
    activeCountDelta: 2,
    activeCountGrowth: { value: 5, hasPrevious: true },
    income: 125,
    incomeGrowth: { value: 12, hasPrevious: true },
  },
  {
    statMonth: '2026年2月',
    current: false,
    merchantCount: 38,
    merchantCountDelta: -5,
    merchantCountGrowth: { value: -12, hasPrevious: true },
    qualifiedCount: 30,
    qualifiedCountDelta: -4,
    qualifiedCountGrowth: { value: -12, hasPrevious: true },
    activeCount: 39,
    activeCountDelta: -2,
    activeCountGrowth: { value: -5, hasPrevious: true },
    income: 108,
    incomeGrowth: { value: -3, hasPrevious: true },
  },
  {
    statMonth: '2026年1月',
    current: false,
    merchantCount: 43,
    merchantCountDelta: 6,
    merchantCountGrowth: { value: 16, hasPrevious: true },
    qualifiedCount: 34,
    qualifiedCountDelta: 7,
    qualifiedCountGrowth: { value: 26, hasPrevious: true },
    activeCount: 41,
    activeCountDelta: 3,
    activeCountGrowth: { value: 8, hasPrevious: true },
    income: 112,
    incomeGrowth: { value: 8, hasPrevious: true },
  },
  {
    statMonth: '2025年12月',
    current: false,
    merchantCount: 37,
    merchantCountDelta: 2,
    merchantCountGrowth: { value: 6, hasPrevious: true },
    qualifiedCount: 27,
    qualifiedCountDelta: 1,
    qualifiedCountGrowth: { value: 4, hasPrevious: true },
    activeCount: 38,
    activeCountDelta: 0,
    activeCountGrowth: { value: 0, hasPrevious: true },
    income: 104,
    incomeGrowth: { value: 11, hasPrevious: true },
  },
  {
    statMonth: '2025年11月',
    current: false,
    merchantCount: 35,
    merchantCountDelta: 1,
    merchantCountGrowth: { value: 3, hasPrevious: true },
    qualifiedCount: 26,
    qualifiedCountDelta: 2,
    qualifiedCountGrowth: { value: 8, hasPrevious: true },
    activeCount: 38,
    activeCountDelta: 1,
    activeCountGrowth: { value: 3, hasPrevious: true },
    income: 94,
    incomeGrowth: { value: 5, hasPrevious: true },
  },
  {
    statMonth: '2025年10月',
    current: false,
    merchantCount: 34,
    merchantCountDelta: -2,
    merchantCountGrowth: { value: -5, hasPrevious: true },
    qualifiedCount: 24,
    qualifiedCountDelta: -1,
    qualifiedCountGrowth: { value: -4, hasPrevious: true },
    activeCount: 37,
    activeCountDelta: -1,
    activeCountGrowth: { value: -2, hasPrevious: true },
    income: 89,
    incomeGrowth: { value: -6, hasPrevious: true },
  },
  {
    statMonth: '2025年9月',
    current: false,
    merchantCount: 36,
    merchantCountDelta: 3,
    merchantCountGrowth: { value: 9, hasPrevious: true },
    qualifiedCount: 25,
    qualifiedCountDelta: 3,
    qualifiedCountGrowth: { value: 14, hasPrevious: true },
    activeCount: 38,
    activeCountDelta: 2,
    activeCountGrowth: { value: 6, hasPrevious: true },
    income: 95,
    incomeGrowth: { value: 9, hasPrevious: true },
  },
  {
    statMonth: '2025年8月',
    current: false,
    merchantCount: 33,
    merchantCountDelta: 3,
    merchantCountGrowth: { value: 10, hasPrevious: true },
    qualifiedCount: 22,
    qualifiedCountDelta: 1,
    qualifiedCountGrowth: { value: 5, hasPrevious: true },
    activeCount: 36,
    activeCountDelta: 1,
    activeCountGrowth: { value: 3, hasPrevious: true },
    income: 87,
    incomeGrowth: { value: 7, hasPrevious: true },
  },
  {
    statMonth: '2025年7月',
    current: false,
    merchantCount: 30,
    merchantCountDelta: -2,
    merchantCountGrowth: { value: -7, hasPrevious: true },
    qualifiedCount: 21,
    qualifiedCountDelta: -2,
    qualifiedCountGrowth: { value: -9, hasPrevious: true },
    activeCount: 35,
    activeCountDelta: -1,
    activeCountGrowth: { value: -4, hasPrevious: true },
    income: 81,
    incomeGrowth: { value: -8, hasPrevious: true },
  },
  {
    statMonth: '2025年6月',
    current: false,
    merchantCount: 32,
    merchantCountDelta: 2,
    merchantCountGrowth: { value: 6, hasPrevious: true },
    qualifiedCount: 23,
    qualifiedCountDelta: 2,
    qualifiedCountGrowth: { value: 10, hasPrevious: true },
    activeCount: 36,
    activeCountDelta: 2,
    activeCountGrowth: { value: 5, hasPrevious: true },
    income: 88,
    incomeGrowth: { value: 6, hasPrevious: true },
  },
  {
    statMonth: '2025年5月',
    current: false,
    merchantCount: 30,
    merchantCountDelta: 0,
    merchantCountGrowth: { value: 0, hasPrevious: true },
    qualifiedCount: 21,
    qualifiedCountDelta: 0,
    qualifiedCountGrowth: { value: 0, hasPrevious: true },
    activeCount: 34,
    activeCountDelta: 0,
    activeCountGrowth: { value: 0, hasPrevious: true },
    income: 83,
    incomeGrowth: { value: 3, hasPrevious: true },
  },
  {
    statMonth: '2025年4月',
    current: false,
    merchantCount: 30,
    merchantCountDelta: null,
    merchantCountGrowth: { value: null, hasPrevious: false },
    qualifiedCount: 21,
    qualifiedCountDelta: null,
    qualifiedCountGrowth: { value: null, hasPrevious: false },
    activeCount: 34,
    activeCountDelta: null,
    activeCountGrowth: { value: null, hasPrevious: false },
    income: 80,
    incomeGrowth: { value: null, hasPrevious: false },
  },
];
